// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdfakhsfhlpsmhjktsie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZmFraHNmaGxwc21oamt0c2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjQ5NzcsImV4cCI6MjA2ODUwMDk3N30.xbBTvGrUuL3t3vvUJ2mOnbe35jHu3cQS75YRi-IQ0Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});